### ISSUE TITLE
support other browsers than Chrome

### ISSUE THREAD

**Issue by inf3rno** [inf3rno/e2e-testing#27]
Todo:
- [ ] - #28 - e2e server capabilities and interface
- [ ] - #29 - e2e client configuration for e2e servers
- [ ] - #30 - how to prevent navigation to an unregistered domain?

In #4 we discussed that we really need some kind of CORS mode, because only Chrome and PhantomJS can disable browser security. In the other browsers even with CORS headers we cannot reach the content of a child window or an iframe. I find it really bad that the browser developers did not give us a way to do so, but let's move on. We can still communicate between cross-origin windows, so we can use `postMessage` to our child windows. I don't want every page on the tested app to inject our testing js code, but that is not necessary. The only thing we need is bypassing the CORS protection on a single page, and that page can load the tested pages in child windows or even in iframes and access their content without any problem. I think we can call the code responsible for that some kind of test server, probably it can be E2EServer. Our E2EClients can request that server with postMessage to do things for them. That's how it will be done, but we need to design some kind of protocol for that and check how it is possible to do our tests without any additional code in this CORS mode. JSONP and it's alternatives gave me the idea to use `Function.toString` and `eval` our tests on the server. Another option if this does not work is building a Selenium like API, which sends the requests as data instead of js code. That requires a lot more work though. Or we can use a hybrid solution too: making a basic api which can be extended by the actual dev using functions, which are evaled on the actual window. This should be the tracking issue of the related work.

**Comment by inf3rno** [comment]
Only Chrome and direct mode will be supported. #56
