### ISSUE TITLE
make navigation stable

### ISSUE THREAD

**Issue by inf3rno** [inf3rno/e2e-testing#6]
Todo:
- [x] #3 - we should prevent anti-iframe scripts and headers to block out e2e tests, not sure whether that is possible. it might depend on whether browser security is turned off
- [x] #4 - we need to decide whether disabled browser security is mandatory, or we support a CORS mode, where the page allows us to run the tests with CORS headers
- [x] #26 - make child window loading stable
- [x] #25 - find a way to detect page loads initiated by the loaded page
- [x] #9 - navigation and page lifecycle what do we need?
- [x] #50 - Implement basic navigation
- [x] #32 - error handling
- [x] #45 - What happens when we are not able to load a page or when we are redirected?

-----------------------------

in #5 I defined how to navigate. I have a very basic code for the client currently:

```js
var E2EClient = function (baseUrl){
    if (!document || !document.body)
        throw new Error("Cannot find DOM document in the actual environment.");
    if (!document.body)
        throw new Error("The DOM content should be loaded before starting the e2e tests.");
    var frame = document.createElement("iframe");
    document.body.appendChild(frame);
    frame.onload = function (){
        this.navigation(null, frame.src, frame.contentWindow);
    }.bind(this);
    frame.onerror = function (errorEvent){
        var error;
        if (errorEvent && errorEvent.error)
            error = errorEvent.error;
        else
            error = Object.create(Error.prototype, errorEvent);
        this.navigation(error, frame.src);
    }.bind(this);
    frame.onabort = frame.onerror;
    this.frame = frame;
    if (!baseUrl)
        throw new Error("Base URL required for the client.");
    this.baseUrl = baseUrl;
};
E2EClient.prototype = {
    constructor: E2EClient,
    busy: false,
    load: function (path, cb){
        if (this.busy)
            throw new Error("Cannot load multiple pages at once.");
        this.busy = true;
        this.cb = cb;
        this.frame.src = this.baseUrl + path;
    },
    navigation: function (error, url, contentWindow){
        if (error)
            throw new Error("Client navigation failure with url " + url + " and message " + error.message);
        if (url.indexOf(this.baseUrl) != 0)
            throw new Error("The client must load pages only with the given base URL.");
        var path = url.substring(this.baseUrl.length);
        var cb = this.cb;
        delete(this.cb);
        this.busy = false;
        cb(contentWindow, path);
    }
};
```

I need to figure out a wait to protect the frame from unwanted navigation, document.write, etc... An inner script can ovverride the location.href any time, which means it can navigate without using my client. Ofc. this is not an usual approach, but it is not impossible. The iframe onload will fire by such rogue navigation too, which can call the callback a second or a third time and make a huge mess. I need to prevent such events, that's why I remove the callbacks now, but it would be better to override the code for Promises. The async-await can handle promises, which is cool, and the lib itself won't be dependent on ES6 features...

I think the minimum requirement for promises is ES5, so IE8+, which is ok for me. I don't want to go back to ES3 with this lib, and I am even thinking on not doing so with my error lib. The only major difference is a lot worse enumeration and I guess no addEventListener by browsers.

**Comment by inf3rno** [comment]
There are 4 possible points for event handlers (if we don't count error or abort):

 - before iframe.src is set
 - after iframe.src is set
 - after window is ready (but document not yet)
 - after document is ready

The 3rd is not trivial to catch if you cannot access the page and add your own js code. The question is whether we need this event handler or not. I think I start a discussion for this.

**Comment by inf3rno** [comment]
I think the upper is an api decision, I moved the sub-issue there and continue this. This issue should cover only setting the new URI, loading the page and notification when a new page was loaded. The latter one can be independent from the previous one, that's what we need to think about more here.

**Comment by inf3rno** [comment]
Another question about the navigation API whether it should support multiple origins by navigation or just a single one.

> For testing it is better to use a baseURI:
> 
> ```js
> const client = new E2EClient({
> 	baseURI: "http://localhost:3333",
> 	sandbox: true
> });
> ```
> 
> With sandbox on, it cannot navigate to a different domain or to an URI, which is not under the base, if there is a base path too. The URI should not end with `/` I think.
> 

So for example if we test google.com and we click on the search results, then it should navigate away for example to wikipedia. Should we allow that navigation or not? Ofc. by this test we should, but it has a cost. If we have a baseURI: "http://localhost:3333/api/v0" for testing, then we can use the sub-path instead of the whole URI for testing. So we can do something like

```js
expect(URITemplate("/customers/:id").match(path)).to.be.ok();
```
instead of

```js
expect(URITemplate("http://localhost:3333/api/v0/customers/:id").match(uri)).to.be.ok();
```

The second one is ugly and can be a big problem, when the domain and port does not come from constants and when we change the root path.

**Comment by inf3rno** [comment]
Security is related to this too:
- [ ] #3 - we should prevent anti-iframe scripts and headers to block out e2e tests, not sure whether that is possible. it might depend on whether browser security is turned off
- [ ] #4 - we need to decide whether disabled browser security is mandatory, or we support a CORS mode, where the page allows us to run the tests with CORS headers

**Comment by inf3rno** [comment]
We got an api from #36 

These are the events:

    page.unload/hide
    navigation.request
    navigation.response
    navigation.error
    page.loading
    page.interactive
    page.load/show
    page.error

These are the operations:

    windowManager.load(resourceIdentifier) -> {page.load: resolve, navigation.error: reject}
    windowManager.execute(function (resolve){...}) -> {res: resolve, err: reject}

**Comment by inf3rno** [comment]
The low level navigation is stable now. It has a few minor bugs, but it works. It does not contain history and pushState support. Those should be added in later versions. I close this. I'll commit tomorrow.
